/* Guess the Average: question pool.
   value = the real number in the question's own unit (so "9.16" means 9.16 million people).
   min/max = slider range (log scale). dec = decimals shown for the answer.
   Every number has a source and year, shown after each guess. Sources disagree on many "per person"
   statistics, so only figures with a clear official source are used.
   cap = hard upper limit for the slider (percentages). min/max are only the base width: play.js shifts the range at random
   for every question so the real value doesn't always sit in the middle.
   diff: easy / medium / hard; a game mixes 3 easy, 4 medium and 3 hard ones. */
const GUESS_Q = [
  /* ---------- easy ---------- */
  { id: "beer", diff: "easy", value: 99, min: 20, max: 300, dec: 0,
    q: { en: "How many litres of beer does the average person in Austria drink per year?", de: "Wie viele Liter Bier trinkt ein Mensch in Österreich im Durchschnitt pro Jahr?" },
    unit: { en: "litres", de: "Liter" },
    fact: { en: "That's about 2 litres every single week, babies included.", de: "Das sind etwa 2 Liter pro Woche, Babys mitgerechnet." },
    src: { name: "Statista / Brewers of Europe", year: 2023, url: "https://www.statista.com/statistics/446028/austria-volume-beer-consumption-per-capita/" } },
  { id: "at-pop", diff: "easy", value: 9.16, min: 1, max: 40, dec: 2,
    q: { en: "How many people live in Austria?", de: "Wie viele Menschen leben in Österreich?" },
    unit: { en: "million people", de: "Mio. Menschen" },
    fact: { en: "About 2 million of them live in Vienna alone.", de: "Etwa 2 Millionen davon leben allein in Wien." },
    src: { name: "Statistik Austria", year: 2024, url: "https://www.statistik.at/fileadmin/announcement/2024/02/20240213Bevoelkerungsstand1.1.2024EN.pdf" } },
  { id: "everest", diff: "easy", value: 8849, min: 2000, max: 30000, dec: 0,
    q: { en: "How high is Mount Everest?", de: "Wie hoch ist der Mount Everest?" },
    unit: { en: "metres", de: "Meter" },
    fact: { en: "Nepal and China agreed on this new figure in 2020, after new measurements.", de: "Nepal und China haben sich 2020 nach neuen Messungen auf diesen Wert geeinigt." },
    src: { name: "Wikipedia: Mount Everest", year: 2020, url: "https://en.wikipedia.org/wiki/Mount_Everest" } },
  { id: "bones", diff: "easy", value: 206, min: 50, max: 800, dec: 0,
    q: { en: "How many bones does an adult human have?", de: "Wie viele Knochen hat ein erwachsener Mensch?" },
    unit: { en: "bones", de: "Knochen" },
    fact: { en: "Babies are born with around 270 to 300. Many of them fuse together as you grow.", de: "Babys kommen mit etwa 270 bis 300 zur Welt. Viele verwachsen beim Wachsen." },
    src: { name: "Wikipedia: Human skeleton", year: 2024, url: "https://en.wikipedia.org/wiki/Human_skeleton" } },
  { id: "vienna-pop", diff: "easy", value: 2.01, min: 0.3, max: 20, dec: 2,
    q: { en: "How many people live in Vienna?", de: "Wie viele Menschen leben in Wien?" },
    unit: { en: "million people", de: "Mio. Menschen" },
    fact: { en: "Vienna passed the 2 million mark in the third quarter of 2023.", de: "Wien hat im dritten Quartal 2023 die Marke von 2 Millionen überschritten." },
    src: { name: "Statistik Austria", year: 2024, url: "https://www.statistik.at/fileadmin/announcement/2024/02/20240213Bevoelkerungsstand1.1.2024EN.pdf" } },

  /* ---------- medium ---------- */
  { id: "steffl-steps", diff: "medium", value: 343, min: 30, max: 3000, dec: 0,
    q: { en: "How many steps lead up the south tower of St. Stephen's Cathedral in Vienna to the watchman's room?", de: "Wie viele Stufen führen im Südturm des Wiener Stephansdoms zur Türmerstube?" },
    unit: { en: "steps", de: "Stufen" },
    fact: { en: "The watchman's room sits at 72 metres, where watchmen once looked out for fires.", de: "Die Türmerstube liegt auf 72 Metern, dort hielten früher Türmer Ausschau nach Bränden." },
    src: { name: "Wien Tourismus", year: 2024, url: "https://www.wien.info/en/see-do/sights-from-a-to-z/st-stephens-cathedral-359690" } },
  { id: "tr-pop", diff: "medium", value: 85.7, min: 5, max: 1000, dec: 1,
    q: { en: "How many people live in Turkey?", de: "Wie viele Menschen leben in der Türkei?" },
    unit: { en: "million people", de: "Mio. Menschen" },
    fact: { en: "About 18 percent of them live in Istanbul alone.", de: "Etwa 18 Prozent davon leben allein in Istanbul." },
    src: { name: "TurkStat, via Daily Sabah", year: 2024, url: "https://www.dailysabah.com/turkiye/turkiyes-population-reaches-86-million-with-family-support-boost/news" } },
  { id: "steffl-height", diff: "medium", value: 136.4, min: 10, max: 1000, dec: 1,
    q: { en: "How tall is the south tower of St. Stephen's Cathedral in Vienna?", de: "Wie hoch ist der Südturm des Wiener Stephansdoms?" },
    unit: { en: "metres", de: "Meter" },
    fact: { en: "It is the third-tallest Gothic church tower in the world, finished in 1433 after 65 years of building.", de: "Er ist der dritthöchste gotische Kirchturm der Welt und wurde 1433 nach 65 Jahren Bauzeit fertig." },
    src: { name: "Wien Tourismus", year: 2024, url: "https://www.wien.info/en/see-do/sights-from-a-to-z/st-stephens-cathedral-359690" } },
  { id: "at-forest", diff: "medium", value: 47.9, min: 1, max: 100, cap: 100, dec: 1,
    q: { en: "What percent of Austria's land is covered by forest?", de: "Wie viel Prozent der Fläche Österreichs sind Wald?" },
    unit: { en: "percent", de: "Prozent" },
    fact: { en: "That's more than 4 million hectares, one of the most forested countries in Europe.", de: "Das sind mehr als 4 Millionen Hektar, eines der waldreichsten Länder Europas." },
    src: { name: "Österreichische Waldinventur 2016–2021", year: 2021, url: "https://www.bmluk.gv.at/service/publikationen/wald/austrian-forest-report-2023.html" } },
  { id: "de-cats", diff: "medium", value: 15.7, min: 0.5, max: 200, dec: 1,
    q: { en: "How many pet cats live in Germany?", de: "Wie viele Hauskatzen leben in Deutschland?" },
    unit: { en: "million cats", de: "Mio. Katzen" },
    fact: { en: "Cats beat dogs there: about 10.5 million dogs.", de: "Katzen schlagen Hunde: Es gibt etwa 10,5 Millionen Hunde." },
    src: { name: "ZZF / IVH (Skopos survey)", year: 2023, url: "https://www.petfoodindustry.com/pet-ownership-statistics/news/15670716/in-germany-cats-remain-the-most-popular-pet" } },

  /* ---------- hard ---------- */
  { id: "istanbul-pop", diff: "hard", value: 15.7, min: 0.5, max: 200, dec: 1,
    q: { en: "How many people live in Istanbul?", de: "Wie viele Menschen leben in Istanbul?" },
    unit: { en: "million people", de: "Mio. Menschen" },
    fact: { en: "That's about 1.7 times as many people as in all of Austria.", de: "Das sind etwa 1,7-mal so viele Menschen wie in ganz Österreich." },
    src: { name: "TurkStat (address-based registration)", year: 2024, url: "https://www.turkishminute.com/2025/02/06/population-density-in-istanbul-26-time-higher-than-national-average-turkstat4/" } },
  { id: "de-pets", diff: "hard", value: 34.3, min: 1, max: 500, dec: 1,
    q: { en: "How many pets (dogs, cats, small animals and pet birds) live in German households?", de: "Wie viele Heimtiere (Hunde, Katzen, Kleintiere und Ziervögel) leben in deutschen Haushalten?" },
    unit: { en: "million pets", de: "Mio. Tiere" },
    fact: { en: "45 percent of all German households have at least one pet.", de: "45 Prozent aller deutschen Haushalte haben mindestens ein Haustier." },
    src: { name: "ZZF / IVH (Skopos survey)", year: 2023, url: "https://www.petfoodindustry.com/pet-ownership-statistics/news/15670716/in-germany-cats-remain-the-most-popular-pet" } },
  { id: "tr-tea", diff: "hard", value: 1300, min: 50, max: 30000, dec: 0,
    q: { en: "How many cups of tea does the average person in Turkey drink per year?", de: "Wie viele Tassen Tee trinkt ein Mensch in der Türkei im Durchschnitt pro Jahr?" },
    unit: { en: "cups", de: "Tassen" },
    fact: { en: "That's almost four glasses every day. Turkey has the highest tea consumption per person in the world.", de: "Das sind fast vier Gläser jeden Tag. Die Türkei hat weltweit den höchsten Teekonsum pro Kopf." },
    src: { name: "FoodNavigator-Asia", year: 2019, url: "https://www.foodnavigator-asia.com/Article/2019/01/16/Turkey-tops-tea-drinking-chart-Each-Turk-drinks-an-average-of-1-300-cups-of-tea-per-year/" } },
  { id: "tr-hazelnut", diff: "hard", value: 70, min: 1, max: 100, cap: 100, dec: 0,
    q: { en: "What share of the world's hazelnuts comes from Turkey?", de: "Welcher Anteil der weltweiten Haselnüsse kommt aus der Türkei?" },
    unit: { en: "percent", de: "Prozent" },
    fact: { en: "It fluctuates between about 64 and 73 percent depending on the year. Turkey also handles over 80 percent of the world's hazelnut trade.", de: "Je nach Jahr schwankt es zwischen etwa 64 und 73 Prozent. Die Türkei wickelt außerdem über 80 Prozent des weltweiten Haselnusshandels ab." },
    src: { name: "FAO", year: 2022, url: "https://www.fao.org/4/x4484e/x4484e03.htm" } },
  /* ---------- more, added later ---------- */
  { id: "eiffel", diff: "easy", value: 330, min: 50, max: 1500, dec: 0,
    q: { en: "How tall is the Eiffel Tower, antenna included?", de: "Wie hoch ist der Eiffelturm mit Antenne?" },
    unit: { en: "metres", de: "Meter" },
    fact: { en: "In hot summers the iron expands and the tower grows by up to 15 centimetres.", de: "In heißen Sommern dehnt sich das Eisen aus, und der Turm wird bis zu 15 Zentimeter höher." },
    src: { name: "Tour Eiffel", year: 2022, url: "https://www.toureiffel.paris/en" } },
  { id: "wien-pop", diff: "easy", value: 2.0, min: 0.3, max: 10, dec: 1,
    q: { en: "How many people live in Vienna?", de: "Wie viele Menschen leben in Wien?" },
    unit: { en: "million people", de: "Mio. Menschen" },
    fact: { en: "Vienna had more than 2 million people already around 1916, then shrank and only passed 2 million again in 2021.", de: "Wien hatte schon um 1916 über 2 Millionen Einwohner, schrumpfte dann und überschritt die Marke erst 2021 wieder." },
    src: { name: "Statistik Austria", year: 2024, url: "https://www.statistik.at" } },
  { id: "glockner", diff: "easy", value: 3798, min: 1000, max: 9000, dec: 0,
    q: { en: "How high is the Grossglockner, Austria's highest mountain?", de: "Wie hoch ist der Großglockner, Österreichs höchster Berg?" },
    unit: { en: "metres", de: "Meter" },
    fact: { en: "Its summit sits on the border between Carinthia and East Tyrol.", de: "Sein Gipfel liegt an der Grenze zwischen Kärnten und Osttirol." },
    src: { name: "BEV (Bundesamt für Eich- und Vermessungswesen)", year: 2023, url: "https://www.bev.gv.at" } },
  { id: "danube", diff: "medium", value: 2850, min: 500, max: 8000, dec: 0,
    q: { en: "How long is the Danube?", de: "Wie lang ist die Donau?" },
    unit: { en: "kilometres", de: "Kilometer" },
    fact: { en: "It flows through ten countries, more than any other river in the world.", de: "Sie fließt durch zehn Länder, mehr als jeder andere Fluss der Welt." },
    src: { name: "Britannica: Danube River", year: 2024, url: "https://www.britannica.com/place/Danube-River" } },
  { id: "un", diff: "medium", value: 193, min: 40, max: 500, dec: 0,
    q: { en: "How many member states does the United Nations have?", de: "Wie viele Mitgliedsstaaten haben die Vereinten Nationen?" },
    unit: { en: "countries", de: "Staaten" },
    fact: { en: "The newest member is South Sudan, which joined in 2011.", de: "Das jüngste Mitglied ist der Südsudan, der 2011 beigetreten ist." },
    src: { name: "United Nations", year: 2024, url: "https://www.un.org/en/about-us/member-states" } },
  { id: "burj", diff: "medium", value: 828, min: 200, max: 3000, dec: 0,
    q: { en: "How tall is the Burj Khalifa in Dubai?", de: "Wie hoch ist der Burj Khalifa in Dubai?" },
    unit: { en: "metres", de: "Meter" },
    fact: { en: "That's about two and a half Eiffel Towers on top of each other.", de: "Das sind etwa zweieinhalb Eiffeltürme übereinander." },
    src: { name: "CTBUH Skyscraper Center", year: 2024, url: "https://www.skyscrapercenter.com/building/burj-khalifa/3" } },
  { id: "riesenrad", diff: "medium", value: 64.75, min: 10, max: 400, dec: 2,
    q: { en: "How tall is the Vienna Giant Ferris Wheel (Riesenrad)?", de: "Wie hoch ist das Wiener Riesenrad?" },
    unit: { en: "metres", de: "Meter" },
    fact: { en: "It opened in 1897 and was the tallest Ferris wheel in the world for decades.", de: "Es wurde 1897 eröffnet und war lange das höchste Riesenrad der Welt." },
    src: { name: "Wiener Riesenrad", year: 2024, url: "https://www.wienerriesenrad.com" } },
  { id: "at-area", diff: "medium", value: 83879, min: 10000, max: 1000000, dec: 0,
    q: { en: "How large is Austria?", de: "Wie groß ist Österreich?" },
    unit: { en: "square kilometres", de: "Quadratkilometer" },
    fact: { en: "The biggest federal state is Lower Austria with around 19,200 square kilometres.", de: "Das größte Bundesland ist Niederösterreich mit rund 19.200 Quadratkilometern." },
    src: { name: "Statistik Austria", year: 2023, url: "https://www.statistik.at" } },
  { id: "moon", diff: "hard", value: 384400, min: 10000, max: 3000000, dec: 0,
    q: { en: "How far away is the Moon from Earth on average?", de: "Wie weit ist der Mond im Durchschnitt von der Erde entfernt?" },
    unit: { en: "kilometres", de: "Kilometer" },
    fact: { en: "The Moon drifts away from Earth by about 3.8 centimetres every year.", de: "Der Mond entfernt sich jedes Jahr um etwa 3,8 Zentimeter von der Erde." },
    src: { name: "NASA", year: 2024, url: "https://science.nasa.gov/moon/" } },
  { id: "circumference", diff: "hard", value: 40075, min: 5000, max: 400000, dec: 0,
    q: { en: "How long is the Earth's circumference at the equator?", de: "Wie lang ist der Erdumfang am Äquator?" },
    unit: { en: "kilometres", de: "Kilometer" },
    fact: { en: "A plane at 900 km/h would need about 44 hours to fly once around.", de: "Ein Flugzeug mit 900 km/h bräuchte etwa 44 Stunden einmal rundherum." },
    src: { name: "Britannica: Earth", year: 2024, url: "https://www.britannica.com/place/Earth" } },
  { id: "universe", diff: "hard", value: 13.8, min: 1, max: 100, dec: 1,
    q: { en: "How old is the universe?", de: "Wie alt ist das Universum?" },
    unit: { en: "billion years", de: "Milliarden Jahre" },
    fact: { en: "The Earth is about 4.5 billion years old, so roughly a third of that.", de: "Die Erde ist etwa 4,5 Milliarden Jahre alt, also etwa ein Drittel davon." },
    src: { name: "ESA / Planck mission", year: 2018, url: "https://www.esa.int/Science_Exploration/Space_Science/Planck" } },
  { id: "mariana", diff: "hard", value: 10935, min: 1000, max: 40000, dec: 0,
    q: { en: "How deep is the Challenger Deep, the deepest known point of the ocean?", de: "Wie tief ist das Challenger-Tief, der tiefste bekannte Punkt des Meeres?" },
    unit: { en: "metres", de: "Meter" },
    fact: { en: "Mount Everest would fit inside, with more than 2 kilometres of water above its summit.", de: "Der Mount Everest würde hineinpassen, und über seinem Gipfel blieben mehr als 2 Kilometer Wasser." },
    src: { name: "NOAA Ocean Exploration", year: 2023, url: "https://oceanexplorer.noaa.gov" } },
  { id: "wall", diff: "hard", value: 21196, min: 1000, max: 200000, dec: 0,
    q: { en: "How long are all the sections of the Great Wall of China together?", de: "Wie lang sind alle Abschnitte der Chinesischen Mauer zusammen?" },
    unit: { en: "kilometres", de: "Kilometer" },
    fact: { en: "It is not one wall but many sections built in different centuries.", de: "Es ist keine durchgehende Mauer, sondern viele Abschnitte aus verschiedenen Jahrhunderten." },
    src: { name: "Britannica: Great Wall of China", year: 2012, url: "https://www.britannica.com/topic/Great-Wall-of-China" } }
];
